// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz0O-34m4eIfttKkdTFelUK2EJCnllGCc',
    appId: '1:982984562092:android:42241501588d447e9ed609',
    messagingSenderId: '982984562092',
    projectId: 'pos-app-e85e4',
    storageBucket: 'pos-app-e85e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2T_c1LsuoIbenGXpGzb1Y1asm_JNrs_0',
    appId: '1:982984562092:ios:fb707360e7f782529ed609',
    messagingSenderId: '982984562092',
    projectId: 'pos-app-e85e4',
    storageBucket: 'pos-app-e85e4.appspot.com',
    androidClientId:
        '982984562092-7bhsklbmipfggqk8v9k9q2eln9euoeso.apps.googleusercontent.com',
    iosClientId:
        '982984562092-t2v6f702fhstau64m11r2087ab4po3df.apps.googleusercontent.com',
    iosBundleId: 'com.spartanmedia.pos.posMobileApp',
  );
}
