const String AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";
const String IS_FIRST_TIME_USER = "IS_FIRST_TIME_USER";

const String EMAIL_ADDRESS_VALIDATOR = 'EMAIL_ADDRESS_VALIDATOR';
const String TOS_VALIDATOR = 'TOS_VALIDATOR';
const String VERIFY_MERCHANT_TASK_OBJECT = 'VERIFY_MERCHANT_TASK_OBJECT';
const String MERCHANT = 'MERCHANT';

const DASBHOARD_VIEW_INDEX = 0;
const HISTORY_VIEW_INDEX = 1;
const REPORT_VIEW_INDEX = 3;
const PROFILE_VIEW_INDEX = 4;

const String BRANCHES = 'branches';
const String SELECTED_BRANCH = 'selectedBranch';
